project:
  type: website
  output-dir: docs/
website:
  title: "Version Control"
  navbar:
    left:
      - href: index.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



